version: '3.0'

services:
  server:
    build:
      context: .
    env_file:
      - .env
    ports:
      - "0.0.0.0:${PORT:8000}:${PORT:8000}"
    volumes:
      - ./app:/app
    depends_on:
      - db
    restart: always
    dns: 8.8.8.8
  db:
    image: mongo:4.4
    ports:
      - "0.0.0.0:6567:27017"
    restart: always
    dns: 8.8.8.8
  grafana:
    image: grafana/grafana:latest
    ports:
      - "0.0.0.0:3000:3000"
    environment:
      - GF_INSTALL_PLUGINS=marcusolsson-json-datasource, gapit-htmlgraphics-panel, cloudspout-button-panel
      - GF_SECURITY_ALLOW_EMBEDDING=true
    volumes:
      - ./grafana/dashboard.yaml:/etc/grafana/provisioning/dashboards/main.yaml
      - ./grafana/datasource.yml:/etc/grafana/provisioning/datasources/main.yaml
      - ./grafana/dashboards:/var/lib/grafana/dashboards
    restart: always
    dns: 8.8.8.8

  core-mosquitto:
    image: eclipse-mosquitto:2
    container_name: core-mosquitto
    restart: unless-stopped
    ports:
      - "1883:1883"
    volumes:
      - ./mosquitto/config:/mosquitto/config
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log

  zigbee2mqtt:
    image: koenkk/zigbee2mqtt:latest
    container_name: zigbee2mqtt
    restart: unless-stopped
    depends_on:
      - core-mosquitto
    ports:
      - "8001:8080"
    volumes:
      - ./config/zigbee2mqtt:/app/data
    environment:
      - TZ=Europe/Paris
